version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: mern_backend_dev
    ports:
      - '5000:5000'
    environment:
      
      MONGODB_URI: "mongodb+srv://joenath376:zs6CyPpVUxdHVWRe@webdatabase.5kijk0l.mongodb.net/?retryWrites=true&w=majority&appName=WebDatabase" # PASTE YOUR FULL URI HERE
      
      PORT: 5000
    restart: unless-stopped
    networks:
      - mern-network

  frontend:
    
    build:
      context: ./myportofolio
      dockerfile: Dockerfile.client
      args:
        
        REACT_APP_API_URL: http://localhost:5000 
    container_name: mern_frontend_dev
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge



