
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./


RUN npm install --only=production


COPY . .


FROM node:20-alpine

WORKDIR /app


COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

EXPOSE 5000


CMD ["node", "/app/api/index.js"]